### ISSUE TITLE
PSCC paper: Gradient of the excitation current

### ISSUE THREAD

**Issue by timmyfaraday** [timmyfaraday/HarmonicPowerModels.jl#1]
The gradient, also the Hessian but not of interest given JuMP limitations, of an interpolation is freely available which means that the autodiff setting could be avoided, possibly speeding up computation.

Issue: to get the gradient at a node `x` of an interpolation `int`, the following is required: `grad = gradient(int,x...)`, which introduces an extra argument in the function call, making it impossible to register as is (status 29/07/21).

Possible fix: add function to the power models data file rather than the interpolation, where `int` is already parsed as an argument.

**Comment by timmyfaraday** [comment]
Both the interpolation and gradient function have been added to the `hdata` dictionary. However, evaluation of the gradient function does not work in JuMP/Ipopt for a coordinate in the feasible space, where the function evaluating the function itself in the terminal works for that given coordinate.

**Comment by frederikgeth** [comment]
was this solved?

**Comment by timmyfaraday** [comment]
Currently, this remains unresolved. However, similar to the excitation, extrapolation of the Splines might resolve this issue.
