### ISSUE TITLE
PSCC Paper: Bugs in Equations?

### ISSUE THREAD

**Issue by frederikgeth** [timmyfaraday/HarmonicPowerModels.jl#12]
https://github.com/timmyfaraday/HarmonicPowerModels.jl/blob/12b24922cfd96114c69605d01c4aa7cf8edd8b3a/src/form/iv.jl#L110

https://github.com/timmyfaraday/HarmonicPowerModels.jl/blob/12b24922cfd96114c69605d01c4aa7cf8edd8b3a/src/form/iv.jl#L146

let's talk later

**Comment by frederikgeth** [comment]
bugs confirmed, will address in PR #11

**Comment by frederikgeth** [comment]
there was another one in the transformer model, but they have all been addressed now

**Comment by timmyfaraday** [comment]
This can be closed?

**Comment by frederikgeth** [comment]
can be closed after you review/merge PR #11
