### ISSUE TITLE
Beyond PSCC Paper: Missing Features

### ISSUE THREAD

**Issue by frederikgeth** [timmyfaraday/HarmonicPowerModels.jl#13]
- RA data input
- complex ratio for harmonics instead of real-value
- specific gen power limit per harmonic?
- test case with dc power
- put slack on lower voltage bound of fundamental, as harmonics can only increase RMS
- detecting floating voltages, e.g. when harmonics are blocked, the current can't flow, but the voltage remains loatinf. this will eventually cause numerical issues
- RA limits specified through matpower extensions instead of hardcoded

**Comment by timmyfaraday** [comment]
I will divide this into seperate issues

**Comment by timmyfaraday** [comment]
Additional simplification for excitation model xfmr:
- voltage limits for sampling follow from the relative magnitude/THD/voltage bounds limits of the connected bus
- given a PowerModels formulation, the optimal `E_formulation` and `I_formulation` should be investigated and implemented

This should significantly reduced the size of the `xfmr_exc` dictionary.
