### ISSUE TITLE
Harmonic State Estimation: Spring Cleaning

### ISSUE THREAD

**Issue by frederikgeth** [timmyfaraday/HarmonicPowerModels.jl#14]
Deadline: 18/04/2023

After merging #11 we have to work on the following to simplify long-term maintenance:

- [x] turn testing scripts into unit tests
- [x] support multiple BH curves per case in a less hacky way (#17)
- [x] separate the fitting and the harmonic replicate, so that it is easier to re-use a fit model
- [x] compare with constant power source on the fundamental, set at the no-load loss of transformer
- [ ] adding RM to matpower file instead of hardcoding
- [ ] adding seperate RMS limit to input file
- [x] develop single-phase harmonic test case in OpenDSS
- [ ] add variants of OpenDSS three-phase cases as single-phase equivalents

**Comment by timmyfaraday** [comment]
I will look into the BH-curve clean-up, as well as the gradient issue mentioned in #1
